# These are supported funding model platforms

github: karlofduty # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: 
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
